name: Update All RSS Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *" # Her 30 dakikada bir otomatik çalışır
  workflow_dispatch: # Elinizle tetikleme butonu

# GitHub Actions botuna depoya dosya yazabilmesi için açıkça izin veriyoruz
permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install beautifulsoup4

      - name: Run RSS Script
        run: |
          python update_news.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add "NewsFolder/*.xml"
          # Eğer değişiklik varsa commit et ve pushla
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update all RSS feeds" && git push)
